### ISSUE TITLE
Usage with Python Test Explorer

### ISSUE THREAD

**Issue by jnjaeschke** [benibenj/vscode-pythonCpp#1]
Is there any way of using this extension in combination with the python test explorer?
The idea would be that I could debug a test using the UI and instead of launching "python -m pytest *mytest*" it immediately attaches the c++ debugger to it.

**Comment by benibenj** [comment]
The python test explorer looks for a configuration of type 'python' and starts the debugger with those setting, if it doesn't find such a configuration it just uses the default configurations. So this means we can't make it start with our debugging settings as we have another debug type. It would be great if we could explicitly select which debugger to use, however, they don't support that currently.

**Comment by bilderbuchi** [comment]
> It would be great if we could explicitly select which debugger to use, however, they don't support that currently.

I also think that this could be quite useful for debugging tests - is there an issue tracking this?

**Comment by benibenj** [comment]
There is no issue tracking this currently which I know of. As the VSCode devs were working on their own testing features/panel, I hoped they would introduce this possibility.
