### ISSUE TITLE
Asks for password everytime - is there a config option to run as sudo by default?

### ISSUE THREAD

**Issue by ephraim271** [benibenj/vscode-pythonCpp#14]
![image](https://user-images.githubusercontent.com/120187203/218043704-d5f475fb-fda3-41b9-9151-91a0b2362f4e.png)
It asks for my password every time I debug, is there a config option which always starts the debugger as sudo so I don't have to type in my password every time?

**Comment by benibenj** [comment]
@ephraim271 No this sadly is not possible.
