### ISSUE TITLE
Working folder not found, open a folder and try again?

### ISSUE THREAD

**Issue by NiKeYiGuN** [benibenj/vscode-pythonCpp#16]

**Comment by benibenj** [comment]
Closing as not related to the extension

**Comment by lcouvreu** [comment]
Hi, I have just installed vscode-pythonCpp and do get the same issue when trying mixed python-C++ debugging.

**Comment by benibenj** [comment]
Make sure in vscode that you have the folder open of the file you wish to debug. If this is the case and you still have a problem, please provide some mire information regarding your setup.

**Comment by NiKeYiGuN** [comment]
> Hi, I have just installed vscode-pythonCpp and do get the same issue when trying mixed python-C++ debugging.

You may need to click on the small green triangle on the left side of run and debug instead of the button at the top

**Comment by lcouvreu** [comment]
Thanks for answers. Problem solved Now. I was using a *.code-workspace file to configure, use now .vscode/launch.json.
