### ISSUE TITLE
Error: the compiler cannot work properly on Mac

### ISSUE THREAD

**Issue by steveshaoucsb** [benibenj/vscode-pythonCpp#5]
<img width="1280" alt="Screen Shot 2022-01-05 at 4 15 13 PM" src="https://user-images.githubusercontent.com/56005374/148308129-c1c5c000-a6fe-4eb1-8e92-ed0f8d9a7c91.png">
<img width="1280" alt="Screen Shot 2022-01-05 at 4 15 22 PM" src="https://user-images.githubusercontent.com/56005374/148308132-74554c30-1f29-4e0f-8a27-c12ecc105287.png">

**Comment by benibenj** [comment]
If you know the required configuration needed you can create a [custom configuration](https://github.com/benibenj/vscode-pythonCpp#custom-configurations)
