### ISSUE TITLE
Support other debuggers than ms-vscode.cpptools

### ISSUE THREAD

**Issue by jacobolofsson** [benibenj/vscode-pythonCpp#7]
This plugin looks really cool, but I am using [`vadimcn.vscode-lldb`](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb), not `ms-vscode.cpptools`. Is there any way to work around it?

Otherwise I think it would be a nice feature to add in the future!

**Comment by lucidfrontier45** [comment]
@jacobolofsson 

I think it's fairly straitforward.

https://github.com/benibenj/vscode-pythonCpp/blob/master/src/pythonCppDebug.ts#L95

This is how we pass pid to cppconf. We just need to pass pid to not only `processId` but also `pid`  which lldb ext uses.

**Comment by benibenj** [comment]
Thanks for the information, I'm having a look at it.

**Comment by lucidfrontier45** [comment]
@benibenj I was trying to make a pull request but it looks you have already done this modificatoin. Thanks for quick fix. I'm looking forward to see the new release.

**Comment by benibenj** [comment]
I have created a new patch. Let me know if the new version works fine for you. Thank you for your help!

**Comment by lucidfrontier45** [comment]
@benibenj I confirmed the latest release works fine with VSCode-LLDB. Thanks.
