### ISSUE TITLE
Enabling pretty printing for gdb

### ISSUE THREAD

**Issue by GuyZilberman** [benibenj/vscode-pythonCpp#9]
Hi,
Is there a way to enable pretty printing in the launch.json file similarly to how it's done in gdb?
I couldn't find a setupCommand attribute for Python C++ Debug.

Thanks!

**Comment by xucian** [comment]
I'm also interested in this

**Comment by benibenj** [comment]
You can use Custom Configurations instead of the default ones if you want to change the gdb configurations.
